name: 'Astronuts AI Action'
description: 'This action runs Astronuts code quality checks on your repositories.'
author: "Astronuts, Inc."
branding:
  icon: bar-chart-2
  color: white

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  token:
    description: "Github Token"
    required: true
  timeout:
    description: "duration after which this github action will end if not completed"
    required: false
  serverUrl:
    description: "Server URL override for internal use only. Not for end user usage."
    required: false
  prReview:
    description: "PR review for Pull Request"
    required: false
  prWalkthrough:
    description: "PR walkthrough for Pull Request"
    required: false
  staticAnalysis:
    description: "Static Analysis for Pull Request Analysis"
    required: false
  configFilePath:
    description: "Path to the configuration file"
    required: false
    default: "./settings.yml"
  rootDir:
      description: "Root directory of the project"
      required: false
      default: "./"
  failOnError:
      description: "Fail the build on error"
      required: false
  language:
      description: "Programming language of the project"
      required: false
  buildSystem:
      description: "The build system used for the project"
      required: false
  testReportsRoot:
      description: "Root directory for test reports"
      required: false
  coverageLib:
      description: "Code coverage library"
      required: false
  coverageReportPaths:
      description: "Paths to code coverage reports"
      required: false

#  sourceLanguage:
#    description: "The source code language"
#    required: true
#  rootDir:
#    description: "Root directory of project"
#    required: false
#    default: "/github/workspace"
#  buildSystem:
#    description: "The build system. If not specified, the action tries to auto-detect one. For a list of supported build systems, see documentation."
#    required: false
#  failOnError:
#    description: "If set to true, the build will fail if the code quality analysis fails. Build will pass silently otherwise."
#    required: false

