name: 'Astronuts Code Quality Check'
description: 'Run Astronuts code quality checks'
author: "Astronuts Inc."
branding:
  icon: bar-chart-2
  color: white

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  sourceLanguage:
    description: "The source code language"
    required: true
  rootDir:
    description: "Root directory of project"
    required: false
    default: "/github/workspace"
